In [1]:
#numpy

In [10]:
#배열
import numpy as np 

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = -5

b = np.array([[1,2,3],[4,5,6]])
#배열 안에 리스트 넣기
print(b.shape)
print(b[0,0],b[0,1],b[0,2])

<class 'numpy.ndarray'>
(3,)
1 2 3
(2, 3)
1 2 3


In [14]:
import numpy as np 

a = np.zeros((2,2))
print(a)

b = np.ones((1,2))
print(b)
#모든 값을 7로 채움
c = np.full((2,2),7) 
print(c)
#단위행렬
d=np.eye(2)
print(d)

e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.52364835 0.93134861]
 [0.33675617 0.09965818]]


In [15]:
#배열 인덱싱

import numpy as np 

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12
b = a[:2,1:3]

print(a[0,1])
print(b)
b[0,0] = 77
print(a[0,1])
#b가 바뀌면 a도 바뀜.

2
[[2 3]
 [6 7]]
77


In [20]:
#슬라이싱
import numpy as np 

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
#행 슬라이싱
row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)

#열 슬라이싱
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [34]:
#정수 배열 인덱싱

import numpy as np 

a = np.array([[1,2],[3,4],[5,6]])
#     [0 1]
# [0]  1 2
# [1]  3 4
# [2]  5 6

print(a[[0,1,2],[0,1,0]])

print (np.array([a[0, 0], a[1, 1], a[2, 0]]))
# [0,1] [0,1] 출력
print(a[[0, 0], [1, 1]])

print (np.array([a[0, 1], a[0, 1]]))



[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [37]:
import numpy as np 

a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(a)

b = np.array([0,2,0,1])

print(a[np.arange(4),b])

a[np.arange(4),b]+=10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [39]:
#boolean array indexing

a = np.array([[1,2],[3,4],[5,6]])

bool_idx = (a>2)

print(bool_idx)

print(a[bool_idx])

print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [41]:
# 자료형

import numpy as np

x = np.array([1,2])
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1,2],dtype=np.int64)
print(x.dtype)

int32
float64
int64


In [43]:
#연산 

import numpy as np 

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))

print(x.dot(v))
print(np.dot(x,v))

print(x.dot(y))
print(np.dot(x,y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [44]:
import numpy as np 

x = np.array([[1,2],[3,4]])

print(np.sum(x))
print(np.sum(x,axis=0))# 열 더하기
print(np.sum(x,axis=1))# 행 더하기


10
[4 6]
[3 7]


In [45]:
import numpy as np 

x=np.array([[1,2],[3,4]])
print(x)

print(x.T)

#rank 1인 배열은 변화 없음
v=np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [60]:
#브로드캐스팅

import numpy as np 

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
v=np.array([1,0,1])
#np.empty_like() 괄호안에 있는 배열과 사이즈가 같은 빈 행렬 생성
y=np.empty_like(x) 
#x에 매 열 마다 v 더하기 

for i in range(4):
    y[i,:]=x[i,:]+v
print(y)

v=np.array([1,0,1,0])
#x에 매 행 마다 v 더하기 
for i in range(3):
    y[:,i]=x[:,i]+v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]
 [10 11 12]]


In [62]:
#행렬 연산 더 빠르게

import numpy as np 

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v,(4,1))
# v 복사본이 vv에 쌓임
print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [63]:
import numpy as np 

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = x + v
print(y)



[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [65]:
# 두배열이 동일한 rank를 가지고 있지 않다면, 낮은 rank의 1차원 배열이 높은 rank 배열의 shape로 간주합니다.
# 특정 차원에서 두 배열이 동일한 크기를 갖거나, 두 배열 중 하나의 크기가 1이라면 그 두 배열은 특정 차원에서 compatible하다고 여겨집니다.
# 두 행렬이 모든 차원에서 compatible하다면, 브로드캐스팅이 가능합니다.
# 브로드캐스팅이 이뤄지면, 각 배열 shape의 요소별 최소공배수로 이루어진 shape가 두 배열의 shape로 간주합니다.
# 차원에 상관없이 크기가 1인 배열과 1보다 큰 배열이 있을 때, 크기가 1인 배열은 자신의 차원 수만큼 복사되어 쌓인 것처럼 간주합니다.

In [80]:
import numpy as np 

v = np.array([1,2,3])
w = np.array([4,5])
#외적 연산
print(np.reshape(v,(3,1))*w)

x = np.array([[1,2,3],[4,5,6]])
print(x+v)

print((x.T+w).T)

print(x+np.reshape(w,(2,1)))

print(x*2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
